import javax.swing.*;
public class StudentResult {
    JFrame f;
    DatabaseOperations db;
    JLabel standard,school,name,roll,maths,science,english,hindi,computer,subject,marks,seperator,seperator1,dseperator1,dseperator;
    JLabel rstandard,rschool,rname,rroll,rmaths,rscience,renglish,rhindi,rcomputer,seperator2,dseperator2,tmarks,rmarks;
    String[] values;
    StudentResult(String search){
        f=new JFrame("Student Result");
        seperator=new JLabel("==================================================================================");
        seperator.setBounds(40,10,400,15);
        f.add(seperator);
        standard=new JLabel("MARKSHEET OF STANDARD : ");
        standard.setBounds(40,30,180,15);
        f.add(standard);
        rstandard=new JLabel();
        rstandard.setBounds(230,30,30,10);
        f.add(rstandard);
        school=new JLabel();
        school.setBounds(280,30,180,15);
        f.add(school);
        seperator1=new JLabel("==================================================================================");
        seperator1.setBounds(40,50,400,15);
        f.add(seperator1);
        name=new JLabel("Student Name : ");
        name.setBounds(200,70,100,15);
        f.add(name);
        rname=new JLabel();
        rname.setBounds(310,70,150,15);
        f.add(rname);
        roll=new JLabel("Roll No.: ");
        roll.setBounds(40,70,100,15);
        f.add(roll);
        rroll=new JLabel();
        rroll.setBounds(150,70,50,15);
        f.add(rroll);
        dseperator=new JLabel("----------------------------------------------------------------------------------------------------");
        dseperator.setBounds(40,90,400,15);
        f.add(dseperator);
        subject=new JLabel("SUBJECT");
        subject.setBounds(40,110,100,15);
        f.add(subject);
        marks=new JLabel("MARKS");
        marks.setBounds(280,110,100,15);
        f.add(marks);
        dseperator1=new JLabel("----------------------------------------------------------------------------------------------------");
        dseperator1.setBounds(40,130,400,15);
        f.add(dseperator1);
        maths=new JLabel("Maths");
        maths.setBounds(40,150,100,15);
        f.add(maths);
        rmaths=new JLabel();
        rmaths.setBounds(300,150,100,15);
        f.add(rmaths);
        science=new JLabel("Science");
        science.setBounds(40,170,100,15);
        f.add(science);
        rscience=new JLabel();
        rscience.setBounds(300,170,100,15);
        f.add(rscience);
        english=new JLabel("English");
        english.setBounds(40,190,100,15);
        f.add(english);
        renglish=new JLabel();
        renglish.setBounds(300,190,100,15);
        f.add(renglish);
        hindi=new JLabel("Hindi");
        hindi.setBounds(40,210,100,15);
        f.add(hindi);
        rhindi=new JLabel();
        rhindi.setBounds(300,210,100,15);
        f.add(rhindi);
        computer=new JLabel("Computer");
        computer.setBounds(40,230,100,15);
        f.add(computer);
        rcomputer=new JLabel();
        rcomputer.setBounds(300,230,100,15);
        f.add(rcomputer);
        dseperator2=new JLabel("----------------------------------------------------------------------------------------------------");
        dseperator2.setBounds(40,250,400,15);
        f.add(dseperator2);
        tmarks=new JLabel("Total Marks: ");
        tmarks.setBounds(40,270,200,15);
        f.add(tmarks);
        rmarks=new JLabel();
        rmarks.setBounds(290,270,100,15);
        f.add(rmarks);
        seperator2=new JLabel("==================================================================================");
        seperator2.setBounds(40,290,400,15);
        f.add(seperator2);
        f.setSize(500,500);
        f.setLayout(null);
        f.setVisible(true);
        db=new DatabaseOperations();
        if(db.connectToDatabase()){
            values=db.studentResults(search);
            rstandard.setText(values[3]);
            school.setText(values[2]);
            rroll.setText(values[0]);
            rname.setText(values[1]);
            rmaths.setText(values[4]);
            rscience.setText(values[5]);
            renglish.setText(values[6]);
            rhindi.setText(values[7]);
            rcomputer.setText(values[8]);
            int totalMarks=Integer.parseInt(values[4])+Integer.parseInt(values[5])+Integer.parseInt(values[6])+Integer.parseInt(values[7])+Integer.parseInt(values[8]);
            rmarks.setText(String.valueOf(totalMarks));
        }

    }
}
